theme = "darcula"

[editor]
line-number = "relative"
rulers = [ 80 ]
color-modes = true
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
parents = false

[editor.statusline]
right = ["selections", "spacer", "spacer", "diagnostics", "spacer", "spacer", "position-percentage", "position"]

[keys.normal]
"F1" = "jump_backward"
"F2" = "goto_definition"
"g" = {"o" = "jump_backward"}